travis:
  secure:
    BINSTAR_TOKEN: GDICg1M8No/qN1Yf/jwRWHpx3fwVgzULWrhyMTRH+fmejMm6V90TKiqxr3/sd1GBCzeA4UZx3B57o/NZunsXgbL+I74TpYWvnzU13G7NjsvsWUbDDReQ/lc6w8Vpi65ypiooOnLPMdkHzD0ycxz4p4JfuGkP5PCQlcEY0LR1CZu0MK5ftKchiD9j9/VM/GhzwXmhKlzRM//34aO9ZwHQBqAgBIBcTEXTkYEnJW0Yyj4fNfKCXumFgXbl+xtd/gOuz2hOWwijQeFN7taZU+Xwkrk03p+QfF1B665O5NfTUjaivFzDvGdT4s7iYhMf6LSd5Ld60pCgQQUTyo4GL9UCzevYbQmYxEY764H6Pi1lHr5X7VyySBYmvQo39/p/Tp4J9cIV6JJYJHwWssn/ShWb+8N2nIOLpXiZVPvw0EiR3nUKTxNPQjEDRxPbvSPcJyh39cxJrOfaUkaH3dd8zVqczx/7YibafHPH8SEX4XeFB3hwyiJephtM9hWHqmeqSEiSs5n32x8OwYHwB210ht28PRg//7AT5p/GqXVlREe8KAWWKSL48xdThPAvGs+0+7k004A+qJ+nO4bstk89LQD8NdKWOfZaKTBI2Uy634ylGkluDq0E1r0e0MomM6I0CelEoZYm5sNRYa9G0b2P2ltVclJIOZ2KfwPZQ20XMQgZMaM=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
